
Description: Instruction to create a RDS Posgres Instance as a Source Database for AWS DMS

Resources:
  RDSPostgresSource:
    Type: AWS::RDS::DBInstance
    Properties: 
      AllocatedStorage: 20
      AutoMinorVersionUpgrade: False
      AllowMajorVersionUpgrade: False
      AvailabilityZone: us-west-2a
      BackupRetentionPeriod: 0


      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: pg-soure-01
      DBName: postgres

      DeleteAutomatedBackups: True
      DeletionProtection: False
      EnablePerformanceInsights: False

      Engine: postgres
      EngineVersion: 12.6

      MasterUsername: postgres
      MasterUserPassword: postgrespwd
      MonitoringInterval: 0

      Port: 5432
      PubliclyAccessible: True